.editorconfig, .gitignore, .pre-commit-config.yaml, .pylintrc, environment.yml, pyproject.toml, requirements-dev.txt, tests/pytest.ini, tests/requirements.txt, tox.ini
Taken from https://github.com/ComPWA/tensorwaves/commit/d46ebcc789143fe4e3ee439a4bf1a9cd2f97ddff
Closes https://github.com/ComPWA/expertsystem/issues/10
=> ci: add local developer tools

.travis.yml, README.md, codecov.yml, doc/index.rst, expertsystem/ui/default_settings.py, expertsystem/ui/system_control.py, setup.py
Closes https://github.com/ComPWA/expertsystem/issues/11
Fixes missing `particle_list.xml` when using `pip install` on MacOS
=> ci: add continuous integration

CONTRIBUTING.md, expertsystem/__init__.py, expertsystem/visualization/__init__.py
Also removes unused graphvis package
=> docs: add description main module

.gitignore, .travis.yml, doc/contribute.rst, environment.yml, expertsystem/__init__.py, setup.py
=> build: drop python support below 3.6

.travis.yml, examples/jupyter/QuickStart.ipynb
=> ci: enforce nbstripout over all notebooks

.travis.yml
Also run `pytest` from the main directory, so better to treat as a separate PR.
=> ci: run pytest from root + add py38 job

.travis.yml, examples/jupyter/QuickStart.ipynb, expertsystem/amplitude/_yaml_adapter.py, expertsystem/amplitude/canonicaldecay.py, expertsystem/amplitude/helicitydecay.py, tests/amplitude/__init__.py, tests/amplitude/expected_recipe.yml, tests/amplitude/test_yaml_recipe.py, tests/channels/test_d0_to_kskpkm.py, tests/channels/test_jpsi_to_gammapi0pi0.py, tests/channels/test_y_to_d0d0barpi0pi0.py
=> feat: add helicity amplity recipe to YAML adapter

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/PULL_REQUEST_TEMPLATE/adr_pull_request.md, .github/PULL_REQUEST_TEMPLATE/pull_request_template.md, .github/pull_request_template.md
Closes #49
Summary of changes:
* add issue templates
* add standard PR template
* add ADR PR template
=> ci: add issue and pull request templates

README.md, doc/index.rst, setup.py
=> doc: define purpose of the PWA Expert System

examples/jupyter/QuickStart.ipynb
=> docs: add heading Quickstart Step 1.4

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/PULL_REQUEST_TEMPLATE/pull_request_template.md, .pre-commit-config.yaml, .travis.yml, .vscode/settings.json, README.md, doc/_templates/genindex.html, doc/_templates/layout.html, doc/adr/0000-use-markdown-architectural-decision-records.md, doc/adr/template.md
Part 1 of #76  
Also updated the pre-commit hooks
=> ci!: add and enforce Prettier formatting

.pre-commit-config.yaml, .travis.yml, .vscode/settings.json, doc/install/install.rst, doc/install/virtual-environment.rst, requirements-dev.txt
=> ci: add and enforce rstcheck

examples/python/JPsiToPi0PipPim.py, expertsystem/amplitude/helicitydecay.py, expertsystem/state/particle.py, expertsystem/state/propagation.py, expertsystem/ui/system_control.py, tests/canonical_formalism/test_ls_coupling.py, tests/particle/test_read_write.py, tests/ui/test_systemcontrol.py
See [here](https://docs.python.org/3/library/enum.html#creating-an-enum), just like we did for https://github.com/ComPWA/tensorwaves/pull/76
=> refactor: switch to Enum class syntax

.vscode/settings.json, doc/conf.py, examples/python/EpEmToChicPipPim.py, examples/python/EpEmToD0D0barPipPim.py, examples/python/JPsiToPi0PipPim.py, expertsystem/__init__.py, expertsystem/amplitude/__init__.py, expertsystem/amplitude/_yaml_adapter.py, expertsystem/amplitude/abstractgenerator.py, expertsystem/amplitude/canonicaldecay.py, expertsystem/amplitude/helicitydecay.py, expertsystem/solvers/__init__.py, expertsystem/solvers/constraint/__init__.py, expertsystem/solvers/constraint/tox.ini, expertsystem/state/__init__.py, expertsystem/state/conservationrules.py, expertsystem/state/particle.py, expertsystem/state/propagation.py, expertsystem/topology/__init__.py, expertsystem/topology/graph.py, expertsystem/topology/topologybuilder.py, expertsystem/ui/__init__.py, expertsystem/ui/default_settings.py, expertsystem/ui/system_control.py, requirements-dev.txt, setup.py, tests/tox.ini, tox.ini
=> ci!: enforce pydocstyle check

.travis.yml, .vscode/settings.json, doc/contribute.rst, doc/install/install.rst, pytest.ini, tests/.coveragerc, tox.ini
=> ci: run pytest and pytest-cov from root dir

.gitignore, .travis.yml, doc/contribute.rst, doc/usage.rst, tox.ini
=> ci!: set up tox test environments

.pre-commit-config.yaml, tox.ini
=> ci: add more pre-commit hooks

tox.ini
See https://pre-commit.com/#temporarily-disabling-hooks
=> ci: simplify tox style check using SKIP

.pylintrc, expertsystem/ui/default_settings.py, expertsystem/ui/system_control.py
#102 removes the need for this weird construct
Also removes the restriction to use `logging` with f-string interpolation
=> refactor: remove SYSTEM_SEARCH_PATHS

expertsystem/ui/system_control.py
Added a check on the formalism type in the stm.
=> feat: add check on formalism type

.github/ISSUE_TEMPLATE/feature_request.md, .gitignore, .prettierrc, doc/adr/0000-use-markdown-architectural-decision-records.md, doc/contribute.rst, doc/install.rst, environment.yml, expertsystem/schemas/README.md, expertsystem/schemas/xml/README.md, pyproject.toml, setup.cfg
=> build!: implement setuptools-scm

.travis.yml, CONTRIBUTING.md, doc/conf.py, doc/contribute.rst, pyproject.toml, setup.cfg
Fixes some mistakes I encountered while comparing to TensorWaves
=> fix: add copy button, faulty links, and doc8

README.md, doc/index.rst, doc/usage.rst, examples/quick_start.ipynb
See https://github.com/ComPWA/tensorwaves/issues/53
=> docs: add Binder for QuickStart

expertsystem/amplitude/canonical_decay.py, expertsystem/data.py, expertsystem/state/conservation_rules.py, expertsystem/state/particle.py, expertsystem/state/propagation.py, tests/canonical_formalism/test_ls_coupling.py, tests/state/conservation_rules/test_cparity.py, tests/state/conservation_rules/test_gparity.py, tests/state/conservation_rules/test_spin.py
=> refactor: merge data and particle Spin classes

.gitignore, .pre-commit-config.yaml, .vscode/settings.json, expertsystem/__init__.py, setup.cfg, tests/data/test_particle.py, tests/state/conservation_rules/test_cparity.py, tests/state/conservation_rules/test_gparity.py, tests/state/conservation_rules/test_mass.py, tests/state/conservation_rules/test_spin.py, tests/state/test_particle.py, tests/ui/test_systemcontrol.py, tox.ini
=> ci!: fix check typing in tests

.github/workflows/pr-name.yml, .gitignore
https://github.com/marketplace/actions/pull-request-linter-action
=> ci: add PR title check

README.md, doc/contribute.rst, doc/index.rst
=> ci: update contribute page

.github/workflows/pypi.yml
Fixes syntax error reported by
https://github.com/ComPWA/expertsystem/actions/runs/196763023
=> fix: repair Publish to PyPI job

expertsystem/io/xml/__init__.py, expertsystem/io/xml/_dump.py, tests/io/test_xml_adapters.py
=> feat: add ComplexEnergyState adapter

expertsystem/data.py, tests/data/test_particle.py
=> feat: implement Parity/Spin.__neg__ operator

expertsystem/data.py
=> feat: print overwrite warning ParticleCollection

.markdownlint.json, README.md, expertsystem/amplitude/_yaml_adapter.py, tests/amplitude/expected_recipe.yml, tests/amplitude/test_yaml_helicity.py
The `expected_recipe.yml` file had not changed in accordance with #154. This would have been noticed with this test.
=> test: validate expected_recipe.yml

expertsystem/particle_list.xml, expertsystem/particle_list.yml, tests/channels/test_d0_to_kskpkm.py, tests/channels/test_nbody_reactions.py, tests/io/test_particle_collection.py
Use the mass eigenstates of K0 instead of K0S and K0L
=> feat: replace K0S/K0L with K0/K0bar

tests/amplitude/test_yaml_canonical.py, tests/amplitude/test_yaml_helicity.py, tests/state/test_particle.py
Closes #185 
Note: speeds up test collection time from 7 sec to 0.3 sec. Tests also run few seconds faster.
=> test: implement fixtures for relevant tests

cspell.json, doc/contribute.rst, examples/particles.ipynb, setup.cfg
=> ci: improve DX with Jupyter Lab

tests/unit/amplitude/expected_recipe.yml, tests/unit/amplitude/test_yaml_helicity.py, tox.ini
Realised after https://github.com/ComPWA/expertsystem/pull/211#discussion_r470691256 that at least the `Parameters` and `Dynamics` sections can be checked as well, because of #112. Not sure why the `Intensity` section is still slightly different though.
=> test: verify YAML parameters and dynamics

doc/conf.py, tests/unit/amplitude/test_yaml_canonical.py, tests/unit/amplitude/test_yaml_helicity.py, tests/unit/conftest.py
=> refactor: share test solutions with fixture

expertsystem/ui/_system_control.py
Oops...
https://pwa.readthedocs.io/projects/expertsystem/en/latest/usage/quickstart.html
=> fix!: remove faulty print statement

examples/particles.ipynb, expertsystem/state/particle.py, expertsystem/state/propagation.py, expertsystem/ui/__init__.py, tests/channels/test_jpsi_to_gamma_pi0_pi0.py, tests/channels/test_y_to_d0_d0bar_pi0_pi0.py, tests/conftest.py, tests/unit/conftest.py, tests/unit/data/test_particle_collection.py, tests/unit/io/test_particle_list.py, tests/unit/ui/test_system_control.py
=> refactor!: remove particle DATABASE global

.github/release-drafter.yml, .github/workflows/release-drafter.yml, .gitignore
Closes #221
See https://github.com/marketplace/actions/release-drafter and https://github.com/ComPWA/expertsystem/labels
=> ci: automate release notes

README.md, doc/conf.py, doc/contribute.rst, doc/index.rst, setup.cfg
Two small additions that were introduced in https://github.com/ComPWA/tensorwaves/pull/120, plus an update to the contribute page
=> docs: add GPLv3+ badge

expertsystem/state/particle.py, expertsystem/topology.py, expertsystem/ui/__init__.py, tests/unit/topology/test_graph.py
=> chore: implement some smaller fixes

cspell.json, doc/contribute.rst, tox.ini
This PR was triggered by https://github.com/ComPWA/expertsystem/pull/247#issuecomment-694197252
=> ci!: add cspell and markdownlint to tox

.pre-commit-config.yaml, doc/_templates/genindex.html, expertsystem/amplitude/helicity_decay.py, expertsystem/io/xml/_build.py, expertsystem/io/xml/_dump.py, expertsystem/io/yaml/validation.py, expertsystem/state/conservation_rules.py, expertsystem/state/particle.py, expertsystem/state/propagation.py, expertsystem/ui/__init__.py, expertsystem/ui/_default_settings.py, expertsystem/ui/_system_control.py, setup.cfg, tests/channels/test_nbody_reactions.py, tests/unit/amplitude/test_yaml_helicity.py, tests/unit/data/test_particle.py, tests/unit/data/test_states.py, tests/unit/io/test_dot.py, tests/unit/state/conservation_rules/test_additive_qn.py, tests/unit/state/conservation_rules/test_g_parity.py, tests/unit/state/conservation_rules/test_ls_coupling.py, tests/unit/state/test_graph_combinatorics.py, tests/unit/ui/test_system_control.py
Black 20.8:
- Support for Python 3.8
- Bug fix "type: ignore" comment
- Lists ending in "," get a forced line break
=> style: upgrade and apply black and prettier

expertsystem/state/particle.py, expertsystem/topology.py, expertsystem/ui/__init__.py, expertsystem/ui/_system_control.py, tests/unit/ui/test_system_control.py
=> refactor: remove dicts in determine_node_settings

expertsystem/ui/__init__.py
=> refactor: convert to dict after int. settings

expertsystem/data.py, tests/unit/test_data.py
I had some problems when using the `ParticleCollection` in some external notebook when doing some list comprehensions involving parity. This PR makes the `Parity` class behave more as expected.
=> feat: improve Parity class

setup.cfg
...because pytest v6 is fully typed
=> ci: upgrade to pytest 6.1.0

.pylintrc, examples/quickstart.ipynb, expertsystem/amplitude/model.py, expertsystem/io/__init__.py, expertsystem/io/xml/__init__.py, expertsystem/io/xml/_build.py, expertsystem/io/xml/_dump.py, expertsystem/io/yaml/__init__.py, expertsystem/io/yaml/_build.py, expertsystem/io/yaml/_dump.py, tests/unit/amplitude/test_io.py
=> feat!: implement load_amplitude_model

expertsystem/data.py, expertsystem/io/_pdg.py, tests/unit/io/test_particle_list.py, tests/unit/io/test_pdg.py, tests/unit/test_data.py
=> feat: ignore name and pid in Particle comparison

expertsystem/amplitude/canonical_decay.py, expertsystem/amplitude/helicity_decay.py, expertsystem/data.py, expertsystem/io/dot.py, expertsystem/nested_dicts.py, expertsystem/solving/__init__.py, expertsystem/state/properties.py, expertsystem/topology.py, expertsystem/ui/__init__.py, expertsystem/ui/_system_control.py, tests/channels/test_d0_to_ks_kp_km.py, tests/unit/amplitude/test_parity_prefactor.py, tests/unit/state/conservation_rules/test_ls_coupling.py, tests/unit/ui/test_system_control.py
=> refactor!: fully abolish old nested dict graph in STM

expertsystem/nested_dicts.py
=> chore: remove obsolete QNConverters

cspell.json, doc/conf.py, expertsystem/_utils.py, expertsystem/io/_pdg.py, expertsystem/solving/conservation_rules.py, expertsystem/state/combinatorics.py, setup.cfg
Closes #306 
A benefit is for instance that this reduces the risk of dependency issues like #241
=> chore: remove numpy as a dependency

.github/workflows/ci.yml, doc/conf.py, environment.yml, expertsystem/__init__.py, expertsystem/amplitude/model.py, expertsystem/data.py, expertsystem/solving/__init__.py, expertsystem/solving/conservation_rules.py, expertsystem/topology.py, pyproject.toml, setup.cfg, tests/unit/conftest.py, tests/unit/test_data.py
=> refactor!: replace dataclasses with attrs

expertsystem/amplitude/canonical_decay.py, expertsystem/amplitude/helicity_decay.py, expertsystem/data.py, expertsystem/solving/__init__.py, expertsystem/state/properties.py, expertsystem/topology.py, expertsystem/ui/__init__.py, expertsystem/ui/_system_control.py, tests/unit/amplitude/test_parity_prefactor.py, tests/unit/state/conservation_rules/test_ls_coupling.py, tests/unit/ui/test_system_control.py
=> refactor!: remove nested dict graph node props

expertsystem/solving/__init__.py, expertsystem/topology.py
=> fix: avoid deep copies of graphs during solving

environment.yml
See https://github.com/ComPWA/tensorwaves/pull/133
=> fix: remove conda-forge channel

cspell.json, expertsystem/reaction/__init__.py, setup.cfg, tox.ini
=> fix: replace progress bar with tqdm

README.md, doc/conf.py, doc/contribute.rst, doc/index.rst, doc/interactive.rst, doc/usage.ipynb, doc/usage/particles.ipynb, doc/usage/visualization.ipynb, doc/usage/workflow.ipynb, environment.yml, expertsystem/__init__.py, setup.cfg
This version center-aligns images by default, which messes up the batches. However, many of the batches are only informative when viewing the GitHub repository. Therefore, the badges on Read the Docs have been reduced and spread over the relevant sub-pages.
=> docs: upgrade to Sphinx Book Theme 0.0.38

tests/channels/test_d0_to_ks_kp_km.py, tests/channels/test_jpsi_to_gamma_pi0_pi0.py, tests/channels/test_y_to_d0_d0bar_pi0_pi0.py
This PR also lets the Y -> DDpipi test run in the CI for the `master` branch.
=> test!: clean up channel tests with facades

cspell.json, test/channels/test_d0_to_ks_kp_km.py, test/conftest.py, test/unit/amplitude/test_io.py, test/unit/amplitude/test_parity_prefactor.py, test/unit/amplitude/test_yaml_canonical.py, test/unit/amplitude/test_yaml_helicity.py, test/unit/io/test_dot.py, test/unit/io/test_particle_list.py
Not only more organised but also 'safer' when using a distributed strategy (see follow-up PR)
=> test: write test output to subfolder

.github/workflows/cd.yml, README.md, docs/api.rst, docs/conf.py, docs/contribute.rst, docs/install.rst, docs/usage/particles.ipynb, setup.cfg, setup.py
Also makes the installation procedure compatible with older versions of `setuptools` (hopefully fixes Colaboratory) and imports the package version in Sphinx
=> docs: simplify and fix installation procedure

docs/usage/workflow.ipynb, src/expertsystem/reaction/__init__.py, src/expertsystem/reaction/_default_settings.py, src/expertsystem/reaction/argument_handling.py, src/expertsystem/reaction/conservation_rules.py, src/expertsystem/reaction/solving.py, tests/channels/test_nbody_reactions.py
Closes #303 
Note that the solving code is not very DRY. But to keep the PR reasonable and make progress faster I chose to have some repetition. This can be improved in another PR
=> feat: support pure edge and node rules in solving

.github/workflows/ci-epic.yml, docs/interactive.ipynb, src/expertsystem/__init__.py, src/expertsystem/reaction/__init__.py, src/expertsystem/reaction/solving.py, tests/channels/test_nbody_reactions.py, tests/unit/test_reaction.py
This is an extension of #360. The idea is to have the latest 'stable' state of the framework in the `master` branch and isolate bigger reworks to an 'epic' branch of the form `epic/*`. The CI for this branch is under 1 minute and does not require review, but still allows for discussion.
=> ci: define GitHub workflow for epic branches

docs/conf.py, docs/develop.rst, docs/index.md, setup.cfg
Improves rendering of the badges. Previously, they had to be rendered with a `list-table` because alignment was centred by default.
=> docs: upgrade to Sphinx Book Theme 0.39

cspell.json, src/expertsystem/reaction/conservation_rules.py, tests/unit/reaction/conservation_rules/test_gellmann_nishijima.py, tests/unit/reaction/conservation_rules/test_helicity_conservation.py, tests/unit/reaction/conservation_rules/test_identical_particle_symmetrization.py, tests/unit/reaction/conservation_rules/test_parity_conservation.py
Closes #268 
Note that this may in the future avoid issues like #376
=> test: add unit tests for all conservation rules

.reqs/doc.txt, .reqs/sty.txt, .reqs/test.txt, requirements-dev.txt, requirements.txt, src/expertsystem/io/_pdg.py, tests/unit/io/test_pdg.py, tests/unit/test_particles.py
62d1d46e should fix failing CD
https://github.com/ComPWA/expertsystem/runs/1460320442?check_suite_focus=true
For verification, see 0ce7630
=> ci: upgrade dependencies

.github/workflows/cd.yml
Closes #411 
Remove all tests from the CD workflow as the CI workflows already ensure that everything is running.
=> ci: make CD and CI compatible

.vscode/settings.json, tests/unit/io/expected_recipe.yml, tests/unit/io/test_dict.py
Also fixes some smaller issues in the tests
=> ci: validate JSON files with schemas in VSCode

src/expertsystem/io/_dict/dump.py, src/expertsystem/schemas/amplitude-model.json, tests/unit/io/expected_recipe.yml
=> refactor: remove Type key from Parameters section

.github/workflows/ci.yml, .github/workflows/linkcheck.yml, .github/workflows/requirements-pr.yml
CI behaviour on draft PR (#289) is too buggy
=> ci: run CI again on draft PR

cspell.json, tox.ini
See https://github.com/ComPWA/PWA-pages/pull/60. Spin-off while working on #461.
=> ci: activate color in tox sphinx-autobuild

docs/usage/visualization.ipynb, reqs/3.6/requirements-dev.txt, reqs/3.6/requirements-doc.txt, reqs/3.6/requirements-sty.txt, reqs/3.7/requirements-dev.txt, reqs/3.7/requirements-doc.txt, reqs/3.7/requirements-sty.txt, reqs/3.8/requirements-dev.txt, reqs/3.8/requirements-doc.txt, reqs/3.8/requirements-sty.txt, reqs/3.9/requirements-dev.txt, reqs/3.9/requirements-doc.txt, reqs/3.9/requirements-sty.txt, setup.cfg, src/expertsystem/reaction/__init__.py, src/expertsystem/reaction/solving.py, src/expertsystem/reaction/topology.py
Spin-off from #459, see https://github.com/ComPWA/expertsystem/pull/459#issuecomment-768917322
=> refactor: decorate more classes with attr.s

.github/workflows/ci.yml
Syncs the dev set-up with that of TensorWaves
=> ci: upload artifacts for build logs

src/expertsystem/amplitude/canonical_decay.py, src/expertsystem/amplitude/helicity_decay.py, src/expertsystem/reaction/topology.py
Makes the code easier to read and also allows for better static typing. Also makes it a bit more easy to refactor if a tuple structure is replaced by a class.
=> fix: use tuple unpacking instead of index

src/expertsystem/amplitude/helicity_decay.py
Functions like `_get_recoil_edge` currently work on a `StateTransitionGraph`. This is misleading: the `Topology` class in itself provides sufficient info.
=> refactor: determine recoil edges from topology

src/expertsystem/reaction/__init__.py, src/expertsystem/reaction/topology.py, tests/unit/reaction/test_combinatorics.py, tests/unit/reaction/test_topology.py
Adds façade functions `create_n_body_decay` and `create_isobar_topology` and simplifies the interface of `SimpleStateTransitionTopologyBuilder` and `InteractionNode` a bit.
=> refactor: improve topology building interfaces

src/expertsystem/reaction/__init__.py, src/expertsystem/reaction/default_settings.py
Closes #355
A better solution would come through #169, but for now this is a necessary feature that only adds to the interfaces.
=> feat: add option to change width factor

tox.ini
See https://github.com/ComPWA/tensorwaves/pull/225
=> ci: allow running notebooks through tox doclive

src/expertsystem/amplitude/kinematics.py
See https://github.com/ComPWA/tensorwaves/pull/227.
=> refactor: rename HelicityKinematics.convert to .transform

docs/usage.ipynb, docs/usage/amplitude.ipynb, docs/usage/dynamics/custom.ipynb, docs/usage/dynamics/lineshapes.ipynb, docs/usage/particle.ipynb, docs/usage/reaction.ipynb, docs/usage/visualize.ipynb
This is mainly important for Google Colaboratory
=> docs: install expertsystem in notebook kernel

.github/workflows/requirements-cron.yml, .github/workflows/requirements-pr.yml, docs/index.md
Added a link to the releases page of this repository from the Sphinx pages.
=> docs: add changelog link to releases

.pre-commit-config.yaml, .pre-commit-hooks/fix_first_nbcell.py, docs/usage.ipynb, docs/usage/amplitude.ipynb, docs/usage/dynamics/custom.ipynb, docs/usage/dynamics/lineshapes.ipynb, docs/usage/particle.ipynb, docs/usage/reaction.ipynb, docs/usage/visualize.ipynb
See https://github.com/ComPWA/tensorwaves/pull/251
=> fix: avoid cell magic in colab cell
