ComPWA/expertsystem

- .pre-commit-config.yaml
- particle_list.xml
- particle_list.yml
- setup.py
One of the end goals of the [XML milestone](https://github.com/ComPWA/expertsystem/milestone/4) is to have `xmltodict` produce a same `dict` structure from `particle_list.xml` as the `dict` that `pyyaml` produces from `particle_list.yml`. This mini PR is just a first step towards that in order to keep the diffs small.
> feat: add yaml particle list

- .pylintrc
- examples/python/EpEmToChicPipPim.py
- examples/python/EpEmToD0D0barPipPim.py
- examples/python/JPsiToPi0PipPim.py
- expertsystem/amplitude/canonicaldecay.py
- expertsystem/amplitude/helicitydecay.py
- expertsystem/state/particle.py
- expertsystem/state/propagation.py
- expertsystem/ui/default_settings.py
- expertsystem/ui/system_control.py
- particle_list.xml
- requirements-dev.txt
- tests/canonical-formalism/test_LSCoupling.py
- tests/channels/test_D0ToKsKpKm.py
- tests/channels/test_JPsiToGammaPi0Pi0Decay.py
- tests/particle/test_read_write.py
- tests/ui/test_systemcontrol.py
- tox.ini
This PR removes XML attributes in both `particle_list.xml` and in the internal handling.
This is a step towards working with YAML, a follow-up PR will introduce that (see temporary diff [here](https://github.com/redeboer/expertsystem/compare/remove-xml-attributes...redeboer:add-yaml-support)).
Closes #25, closes #26, and closes #31
> refactor!: remove XML attributes

- expertsystem/state/particle.py
- requirements.txt
- tests/.gitignore
- tests/particle/test_read_write.py
The `particle_list` now contains `dict`s instead of `OrderedDict`, so that it can be processed by `pyyaml`. The structure of `particle_list` is still the same though and does not yet reflect the [structure of `particle_list.yml`](https://github.com/ComPWA/expertsystem/blob/74e9bf34825155c7b044375f05e140e196b0e036/particle_list.yml).
> feat: add yaml support for particle list

- setup.py
Made a mistake with the version in #59... I thought to have [0.1.1](https://github.com/ComPWA/expertsystem/milestone/7) implement YAML for the helicity formalism (so it can be used in tensorwaves), while [0.1.2](https://github.com/ComPWA/expertsystem/milestone/8) implements the canonical formalism.
> build: bump version to 0.1.1-alpha

- .github/PULL_REQUEST_TEMPLATE/adr_pull_request.md
- .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Turns out that the PR templates introduced in #52 aren't too great (the issue templates are still useful). This problem is particularly problematic when working with the [vscode GitHub PR extension](https://code.visualstudio.com/docs/editor/github): without a PR template (as is the case in tensorwaves), vscode nicely extracts most info for the PR from the incoming commits, but this info is overruled by the PR template.
> ci: remove GitHub PR templates

- .editorconfig
- .pre-commit-config.yaml
- .prettierignore
- .travis.yml
- .vscode/settings.json
- cspell.json
- doc/contribute.rst
- setup.py
Note that:
1. `cspell` has not been added as a pre-commit hook, because it requires the system to have `npm`
2. `cspell` is not enforced through Travis
> ci: add cspell support

- cspell.json
- doc/adr/0000-use-markdown-architectural-decision-records.md
- doc/contribute.rst
This is a rather trivial PR but part of a series. Key point is that we now follow a third option to ignore words -- inline in specific files -- as to keep the `cspell.json` small.
_Part of the PR series mentioned in https://github.com/ComPWA/expertsystem/issues/22#issuecomment-654052278_
> ci: simplify cspell set-up

- .travis.yml
- doc/contribute.rst
- tox.ini
* Speed up main `tox` job by avoiding check on external links (`linkcheck`) and not executing Jupyter notebooks
* Define `docnb` job for executing notebooks (and building them into the docs)
* Simplify command `tox -e sty` (previously `tox -e style`)
_Follow-up to #96_
_Part of the PR series mentioned in https://github.com/ComPWA/expertsystem/issues/22#issuecomment-654052278_
> ci: improve tox usage with more specific jobs

- expertsystem/state/particle.py
- expertsystem/ui/default_settings.py
- expertsystem/ui/system_control.py
- tests/particle/test_read_write.py
- tox.ini
While removing the `default_particle_list_search_paths` (this can be done since #102), I figured I'd address the smaller style issues below in a smaller PR first.
* Add typing hints to `default_settings` module
* Rename `particle_list` to `DATABASE` (this global should eventually be replaced by some sort of `ParticleCollection` singleton, but that first requires #42)
* Capitalize globals of `default_settings`
> refactor: capitalize globals

- tox.ini
Locally, tests marked `slow` are not run anymore by `tox`. This was annoying because you just want to run `tox` whenever you make a PR and don't want to wait for that several minutes.
If you want to run all tests, use `tox -e test`.
Note that not running the slow tests hardly affects the benchmarks, but greatly increases speed:
| command                | duration | coverage |
|------------------------|----------|----------|
| `pytest`               | 133s     | 74.82%   |
| `pytest -m "not slow"` |  17s     | 74.51%   |
> ci: speed up tox further

- examples/quickstart.ipynb
- expertsystem/ui/__init__.py
- tests/amplitude/test_parity_prefactor.py
- tests/amplitude/test_yaml_canonical.py
- tests/amplitude/test_yaml_helicity.py
- tests/canonical_formalism/test_ls_coupling.py
- tests/channels/test_d0_to_kskpkm.py
- tests/channels/test_jpsi_to_gammapi0pi0.py
- tests/channels/test_nbody_reactions.py
- tests/channels/test_y_to_d0d0barpi0pi0.py
- tests/ui/test_systemcontrol.py
Closes #91 
Amplitude model recipe writing can now be done directly from the STM. This removes the need to first create e.g. a `HelicityAmplitudeGenerator`.
> feat: add write amplitude model from STM

- expertsystem/amplitude/_yaml_adapter.py
- expertsystem/amplitude/helicity_decay.py
- expertsystem/data.py
- expertsystem/io/xml/_build.py
- expertsystem/io/xml/_dump.py
- expertsystem/io/yaml/_build.py
- expertsystem/io/yaml/_dump.py
- expertsystem/particle_list.xml
- expertsystem/schemas/yaml/particle-list.json
- expertsystem/state/particle.py
- tests/amplitude/expected_recipe.yml
- tests/amplitude/test_yaml_helicity.py
- tests/io/test_particle_collection.py
- tests/state/test_particle.py
_Breaking change: decay info is not added to the recipe anymore! Therefore the tests had to be modified and functionality has been lost. Dynamics has to be added by the user in another phase, but this requires a big change in the interface_
Note also that the values of the internal nested `dict`s of `particle.DATABASE` have become `int`/`float`, not `str`. That's why the `QNConverter` converter classes don't cast to `str` anymore (see also #122)
> refactor!: ParticleCollection -> particle.DATABASE

- .gitignore
- expertsystem/amplitude/_yaml_adapter.py
- expertsystem/data.py
- expertsystem/io/xml/_build.py
- expertsystem/io/xml/_dump.py
- expertsystem/io/yaml/_build.py
- expertsystem/io/yaml/_dump.py
- expertsystem/particle_list.xml
- expertsystem/particle_list.yml
- expertsystem/schemas/yaml/particle-list.json
- tests/.gitignore
- tests/amplitude/expected_recipe.yml
- tests/data/test_particle.py
- tests/io/test_particle_collection.py
Particle mass and width have become `float`, that is, the uncertainty in these attributes (embedded through `MeasuredValue`) is not available anymore, as it is not used internally by the `expertsystem`.
Closes #123
> refactor!: remove MeasuredValue

- .pylintrc
- .travis.yml
- README.md
- cspell.json
- doc/conf.py
- doc/index.rst
- environment.yml
- expertsystem/__init__.py
- expertsystem/data.py
- expertsystem/io/xml/__init__.py
- expertsystem/io/xml/_build.py
- expertsystem/io/xml/_dump.py
- expertsystem/io/yaml/__init__.py
- expertsystem/io/yaml/_build.py
- expertsystem/io/yaml/_dump.py
- pyproject.toml
- setup.cfg
- tests/data/test_particle.py
- tests/io/test_particle_collection.py
Closes #127
**Major changes**
* Dropped support for Python 3.6 in order to use [`dataclasses`](https://docs.python.org/3/library/dataclasses.html)
* Removed type hints, see #149
> feat: define quantum state interfaces

- labels.toml
- setup.cfg
See #155
The idea of this PR is to have a back-up of the existing issue labels (mainly for the fancy colours). A follow-up PR (#160) will then import the new labels (categories only).
For more info, see
https://github.com/marketplace/actions/manage-issue-labels
> ci: import current GitHub issue labels

- .github/workflows/ci.yml
- .github/workflows/linkcheck.yml
- .pre-commit-config.yaml
- codecov.yml
- tests/channels/test_d0_to_kskpkm.py
- tox.ini
This PR allows one to quickly ensure with
```bash
tox -e py  # fast tests only
```
that test coverage does not drop significantly.
> ci: increase minimal test coverage

- .gitignore
- .vscode/settings.json
- codecov.yml
- tox.ini
This will lower the test coverage from 93% to 89%, but the lower value is the more accurate. When using [Coverage Gutters](https://marketplace.visualstudio.com/items?itemName=ryanluker.vscode-coverage-gutters) (see [contribute page](https://pwa.readthedocs.io/projects/expertsystem/en/0.3.0-alpha/contribute.html#testing)), branch coverage provides a more reliable overview.
See also https://coverage.readthedocs.io/en/latest/branch.html.
**Progress**
> test!: switch to branch coverage

- expertsystem/amplitude/abstract_generator.py
- expertsystem/state/particle.py
- setup.cfg
- tests/state/test_particle.py
Previously, we made the mistage to use the `mypy` option `ignore_errors` to completely ignore certain modules. This also removes checks on functions that use types from those ignored module. Using `disallow_untyped_defs = False` would have been sufficient.
Note that this change pointed out some mistakes in the `create_particle` builder functions. These have been fixed.
> ci: remove mypy module ignores

- expertsystem/io/xml/_build.py
- expertsystem/io/xml/_dump.py
- expertsystem/io/yaml/_build.py
- expertsystem/io/yaml/_dump.py
- expertsystem/particle_list.xml
- expertsystem/particle_list.yml
- tests/amplitude/expected_recipe.yml
- tests/io/test_particle_collection.py
Set `isospin=Spin(...)` for all hadrons and `None` (undefined) for leptons and bosons.
> fix!: distinguish isospin 0 and None

- .gitignore
- .vscode/extensions.json
- examples/visualization.ipynb
- expertsystem/io/dot.py
- expertsystem/state/particle.py
- tests/unit/io/test_dot.py
- tests/unit/topology/test_graph.py
Previously, DOT visualisation would crash if it got an uninitialised `StateTransitionGraph` (because it doesn't have edge properties). Now, the edge ID is used instead if there are no edge properties. In addition, if there are edge properties, the spin projection is printed as well. A `list` of solutions can now also be rendered in one graphviz file.
A quick demo is available under `test_graph.py`.
Also includes some minor fixes and refactorings to the `particle` submodule.
> feat: visualize list of StateTransitionGraphs

- .github/release-drafter.yml
Last one... hopefully. This should fix:
> ci: fix $CONTRIBUTORS in release drafter

- setup.cfg
TensorFlow requires numpy<1.19
We'll make a release 0.4.0a1 after this for `tensorwaves`
> build: downgrade to numpy 1.18.0

- expertsystem/amplitude/canonical_decay.py
- expertsystem/amplitude/helicity_decay.py
- expertsystem/state/particle.py
- expertsystem/ui/__init__.py
- expertsystem/ui/_system_control.py
- tests/channels/test_jpsi_to_gamma_pi0_pi0.py
- tests/unit/amplitude/test_parity_prefactor.py
- tests/unit/amplitude/test_yaml_canonical.py
- tests/unit/ui/test_system_control.py
Lead-up to #231: the list of solutions by `StateTransitionGraph.find_solutions` now does not contain the kinematic combinatorics anymore. This responsibility has been moved to the amplitude builders.
> refactor!: move particle combinatorics

- examples/particles.ipynb
- expertsystem/data.py
- expertsystem/io/_pdg.py
- expertsystem/io/xml/__init__.py
- expertsystem/io/xml/_build.py
- expertsystem/io/xml/_dump.py
- expertsystem/io/yaml/_build.py
- expertsystem/io/yaml/_dump.py
- expertsystem/state/particle.py
- tests/channels/test_d0_to_ks_kp_km.py
- tests/unit/data/test_particle.py
- tests/unit/data/test_particle_collection.py
- tests/unit/data/test_states.py
- tests/unit/io/test_pdg.py
- tests/unit/io/test_xml_adapters.py
This PR 
- removes the `QuantumState` and `ComplexEnergyState` classes which will not be used in this form internally
- merges  the `ComplexEnergy` functionality with `Particle` and flattens the quantum number structure in `Particle`
This influences issue #231 and should be easier to tackle
> refactor!: remove QuantumState classes

- .github/workflows/ci.yml
- .vscode/extensions.json
- .vscode/settings.json
- codecov.yml
- cspell.json
- expertsystem/data.py
- expertsystem/io/_pdg.py
- pyrightconfig.json
Pylance seems to be the direction in which VSCode is moving
https://devblogs.microsoft.com/python/announcing-pylance-fast-feature-rich-language-support-for-python-in-visual-studio-code/
The original motivation to switch to Pylance was **improved language navigation**, but it also provides diagnostics. In the long run, we may want to implement `pyright` in the CI as well, just like the `npm` packages `cspell` and `markdownlint`.
_Rebased on #246_
> ci: implement pyright and VSCode Pylance

- .pylintrc
- expertsystem/state/particle.py
- expertsystem/topology.py
- expertsystem/ui/__init__.py
- expertsystem/ui/_system_control.py
- tests/unit/topology/test_graph.py
- tests/unit/ui/test_system_control.py
- tox.ini
Improvements to the `topology` module in order to distinguish the different initialize stages of `StateTransitionGraph`s:
* Extracted `Topology` base class (no node/edge properties) from `StateTransitionGraph`
* Nodes have become a `set`
* Protected nodes and edges of `Topology`
* Type-templated edge properties of `StateTransitionGraph`
* `Edge` has become a `dataclass`
_Rebased on #247_
> refactor: extract Topology class

- expertsystem/amplitude/abstract_generator.py
- expertsystem/amplitude/canonical_decay.py
- expertsystem/amplitude/helicity_decay.py
- expertsystem/state/properties.py
- setup.cfg
Part of #43, step towards #65.
After this PR, only the `state.propagation` is left untyped.
The type hints help with the refactoring, especially in combination with pylance. Note that the type hints for the nested `dict` are rather loose (just "`dict`") because this is the part that will be refactored out.
> feat: add type hints amplitude module

- .pre-commit-config.yaml
- doc/contribute.rst
- doc/index.rst
- setup.cfg
This correctly enforces a line width of 79 in `.rst` files.
> ci: implement doc8 check

- expertsystem/solving/conservation_rules.py
An attempt to make clearer that the type hints of the `Rule` derivative classes have an important dynamic role as well.
> docs: improve docstring of Rule

- .github/workflows/ci.yml
- .github/workflows/linkcheck.yml
Only run GitHub Actions if PR is ready for review (not draft status).
> ci: ignore draft pull requests

- expertsystem/amplitude/canonical_decay.py
- expertsystem/data.py
- expertsystem/nested_dicts.py
- expertsystem/solving/__init__.py
- expertsystem/state/properties.py
- expertsystem/ui/__init__.py
- expertsystem/ui/_system_control.py
- tests/unit/state/conservation_rules/test_ls_coupling.py
- tests/unit/ui/test_system_control.py
Closes #283 
Note that the Result is currently a `Generic` to allow the StateTransitionManager to return the old type of Result, while the solving module is using the new `ParticleWithSpin`.
> refactor!: change solutions type of Result class

- setup.cfg
Even though #43 has been closed, the `expertsystem` as a package is not yet [PEP-561](https://www.python.org/dev/peps/pep-0561/) compatible due to [this](https://mypy.readthedocs.io/en/latest/installed_packages.html#making-pep-561-compatible-packages).
> fix: make expertsystem PEP-561 compatible

- doc/interactive.rst
- expertsystem/data.py
- tests/unit/test_data.py
Closes #294 
The `create_antiparticle` is now also tested for all particles in the PDG that have a counterpart with -PID.
> feat: implement Particle.__neg__ operator

- setup.cfg
https://packaging.python.org/guides/distributing-packages-using-setuptools/#project-urls
Result would be something like this on https://pypi.org/project/expertsystem
> docs: add PyPI project URLs

- expertsystem/reaction/conservation_rules.py
- expertsystem/reaction/solving.py
- expertsystem/ui/__init__.py
- setup.cfg
- tests/unit/reaction/conservation_rules/test_spin.py
- tox.ini
Adds the [`flake8-bugbear` ](https://github.com/PyCQA/flake8-bugbear) extension, which seems to be stable and used a lot. Also points some potential design flaws (marked `# noqa: B009/B010`) that might be fixed later on with #309.
> ci: activate flake8 bugbear

- expertsystem/schemas/yaml/amplitude-model.json
There's a mistake in the JSON validation schema for the YAML recipe file: it does not reflect the structure of a `RecoilSystem`, which has a `list` of `int`s only:
https://github.com/ComPWA/expertsystem/blob/c4f1769c7c49915ca363b8402e82826b3b30c922/expertsystem/amplitude/model.py#L329-L332
> fix: validate list-only in recoil systems

- cspell.json
- doc/.gitignore
- doc/conf.py
- doc/index.rst
- setup.cfg
Also adds links to related projects in the sidebar and hides the ADR pages.
Note: `pydeps` requires Graphviz at runtime. However, the `subprocess.call` won't signal a fatal error once `pydeps` fails and then the image simply won't be added. On RTD, Graphviz is available (see the graph vizualisation module), and the image will be rendered if it is available.
> docs: visualize module dependencies

- doc/interactive.rst
- examples/particles.ipynb
- examples/quickstart.ipynb
- expertsystem/particle.py
- tests/unit/test_particles.py
Now that `ParticleCollection` mimicks a `set`, it has become a bit bothersome to get a list of particle names. This has some rather ugly effects here, for instance:
https://pwa.readthedocs.io/projects/expertsystem/en/0.5.0/usage/particles.html#Finding-particles
> feat: implement ParticleCollection.names

- expertsystem/reaction/_system_control.py
- tests/channels/test_nbody_reactions.py
Allow only electromagnetic interaction type on nodes that have at least one gamma as edge
> fix!: allow only EM on nodes with gamma

- expertsystem/schemas/yaml/amplitude-model.json
The JSON validation schema for YAML had a bug with regard to `PreFactor`.
Fix is simple, but it took some time, because I tried to write a test for this. Eventually I gave up with that, because I keep running in some `pytest` loops, see #.
> fix: repair PreFactor key in YAML validation

- .gitignore
- cspell.json
- doc/conf.py
- expertsystem/reaction/_default_settings.py
- expertsystem/reaction/argument_handling.py
- expertsystem/reaction/conservation_rules.py
- expertsystem/reaction/quantum_numbers.py
- expertsystem/reaction/solving.py
- pyproject.toml
- setup.cfg
- tests/channels/test_nbody_reactions.py
- tests/unit/reaction/conservation_rules/test_additive_qn.py
- tests/unit/reaction/conservation_rules/test_c_parity.py
- tests/unit/reaction/conservation_rules/test_g_parity.py
- tests/unit/reaction/conservation_rules/test_spin.py
Extract the Rule argument handling code into a separate module. Also allow more flexible arguments and improve type annotation handling via inspect. Exchange the Rule interface with a `Protocol` (`ConservationRule`) and define a second type of Rule (`EdgeQNConservationRule`), which does not require any node quantum numbers.
This prepares things for issue #303
> refactor!: improve Rule argument handling code

- expertsystem/particle.py
- tests/unit/test_particles.py
Small enhancement I found to be useful when defining the initial and final states and making a typo. Results in the following https://github.com/ComPWA/expertsystem/blob/64d4ec18028063ccc1f2226925e545a5e65afd22/tests/unit/test_particles.py#L342-L350
> fix: sort ParticleColl. getitem candidates by mass

- doc/contribute.rst
- tox.ini
Currently, it takes around one minute to run `tox -e py` (the default test environment). This has been reduced to a third, because the test coverage job has been moved to the specialised command `tox -e cov`. See updated contribute page.
> ci: split tox coverage job

- .vscode/settings.json
- doc/usage/quickstart.ipynb
- doc/usage/visualization.ipynb
- expertsystem/io/__init__.py
- expertsystem/io/_dot.py
- expertsystem/reaction/solving.py
- expertsystem/reaction/topology.py
- tests/unit/io/test_dot.py
- tests/unit/reaction/test_solving.py
Extract a `List[StateTransitionGraph[Particle]]` (without spin projections) from the `Result` class. This is useful when visualising solutions, e.g.:
> feat: implement Result.get_particle_graphs

- doc/usage/visualization.ipynb
- expertsystem/io/_dot.py
- expertsystem/reaction/solving.py
- tests/unit/io/test_dot.py
- tests/unit/reaction/test_solving.py
_Rebased on #336_
As a follow-up to #336, I added some more functionality to the `Result` class that can help when investigating allowed transitions. There's now `Result.collapse_graphs` which returns a `list` of `StateTransitionGraph` that are unique up to isomorphism of the topology (well, sounds fancy, but I just check if the ID-to-particle `dict`s of the outer edge properties are different). The edge properties are `ParticleCollection`s that have all particles of the original graphs collected.
The `io.conver_to_dot` function can handle it, resulting in something like that. Ugly, I know, but that's just how `graphviz` renders it... Usage is described in the renewed visualization notebook (preview [here](https://pwa--341.org.readthedocs.build/projects/expertsystem/en/341/usage/visualizat …
> feat: visualize collapsed graphs

- cspell.json
- doc/usage/particles.ipynb
- doc/usage/quickstart.ipynb
- doc/usage/visualization.ipynb
Since #348, the progress bar is visible in notebooks. Unfortunately, that also means the logs are rendered in the usage pages. This PR avoids that, as well as cleaning up the pages with [margin notes](https://sphinx-book-theme.readthedocs.io/en/latest/layout.html#margins).
> docs: hide logs from example pages

- docs/conf.py
- src/expertsystem/reaction/solving.py
Causes problems in the `Result` class, at least for final states with more than 3 particles.
<details>
<summary>Snippet to cause that shows the bug</summary>
```python
import graphviz
from expertsystem.reaction import InteractionTypes, StateTransitionManager
stm = StateTransitionManager(
initial_state=["D(s)+"],
final_state=["pi0", "pi+", "K+", "K-"],
allowed_intermediate_particles=["phi(1020)", "rho(770)+"],
)
stm.set_allowed_interaction_types([InteractionTypes.Strong, InteractionTypes.EM]),
stm.add_final_state_grouping([["pi0", "pi+"], ["K+", "K-"]])
graph_interaction_settings = stm.prepare_graphs()
result = stm.find_solutions(graph_interaction_settings)
print("Solutions:", len(result.solutions))
dot = es.io.convert_to_dot(result.collapse_graphs())
graphviz.Source(dot)
```
</details>
> fix: use defaultdict in convert_to_names

- .github/workflows/cd.yml
- pyproject.toml
Here's a first attempt at (partially) fixing #377. I'm not fully sure whether it works, but we want to have the #376 released for `tensorwaves`.
To be clear, trying to fix two things here:
> fix: build wheel and fix deploy job

- .github/workflows/cd.yml
- docs/conf.py
Closes #377
The CD job still does not trigger correctly. Hope this PR does the trick.
https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-python#publishing-to-package-registries
(which uses `twine`) instead of
https://packaging.python.org/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
Edit: `(pre)released` types work. Was tested on a fork.
> ci: fix release to pypi upon (pre)release

- .editorconfig
- .github/workflows/cd.yml
- .github/workflows/ci.yml
- .pre-commit-config.yaml
- cspell.json
- setup.cfg
- tox.ini
- Removes the need to `npm`-install `markdownlint`.
- Upgrades `pre-commit`.
- Also did some alphabetical sorts in config files.
> ci: implement markdownlint pre-commit hook

- docs/usage/workflow.ipynb
- src/expertsystem/io/_xml/_build.py
- src/expertsystem/io/_xml/_dump.py
- src/expertsystem/io/_yaml/_dump.py
- src/expertsystem/schemas/yaml/amplitude-model.json
- tests/unit/amplitude/expected_recipe.yml
- tests/unit/amplitude/test_yaml_canonical.py
- tests/unit/amplitude/test_yaml_helicity.py
- tests/unit/conftest.py
There was a bug when dumpin an `AmplitudeModel` containing a `RelativisticBreitWigner` to YAML or XML. This PR fixes it.
Note: better solution is through #383, but this is more of a hot-fix that is required for TensorWaves, see e.g.
https://github.com/ComPWA/tensorwaves/pull/179/checks?check_run_id=1454030793
> fix: correctly dump Breit-Wigner

- cspell.json
- docs/conf.py
- docs/usage/workflow.ipynb
- src/expertsystem/amplitude/__init__.py
- src/expertsystem/amplitude/canonical_decay.py
- src/expertsystem/amplitude/helicity_decay.py
- src/expertsystem/io/_dot.py
- src/expertsystem/io/_yaml/_dump.py
- src/expertsystem/reaction/__init__.py
- src/expertsystem/reaction/_default_settings.py
- src/expertsystem/reaction/_system_control.py
- src/expertsystem/reaction/argument_handling.py
- src/expertsystem/reaction/combinatorics.py
- src/expertsystem/reaction/default_settings.py
- src/expertsystem/reaction/solving.py
- src/expertsystem/reaction/topology.py
- tests/channels/test_jpsi_to_gamma_pi0_pi0.py
- tests/channels/test_y_to_d0_d0bar_pi0_pi0.py
- tests/unit/amplitude/test_parity_prefactor.py
- tests/unit/conftest.py
- tests/unit/io/test_dot.py
- tests/unit/reaction/test_combinatorics.py
- tests/unit/reaction/test_solving.py
- tests/unit/reaction/test_system_control.py
- tests/unit/reaction/test_topology.py
- Change interface of Solver, to accept a new data structure ProblemSet
instead of the previous arguments. Also introduce a new data structure
QNResult which is now also the new return type of the Solver interface.
This removes the StateTransitionGraph and Particle from the module.
- Move Result to the reaction module to keep the interface for
find_solutions of the STM stable.
- Change prepare_graphs and underlying code to create_problem_sets. This
instead creates ProblemSet data structures that can be fed to the
solving module.
- Adapt other code pieces to these changes.
Closes #380 
Connects to #266
> refactor!: make solving module graph independent

- .github/workflows/ci.yml
- src/expertsystem/reaction/__init__.py
- src/expertsystem/reaction/solving.py
- tests/channels/test_y_to_d0_d0bar_pi0_pi0.py
In case allowed intermediate states are specified, reduce the edge
quantum numbers for intermediate edges to match the given allowed
states.
This can dramatically reduce the runtime, when intermediate states are
explicitly specified.
> feat: reduce edge qn domains to allowed states 

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
https://github.com/ComPWA/expertsystem/issues/419#issuecomment-755348567
> ci: improve issue templates

- src/expertsystem/amplitude/helicity_decay.py
- tests/channels/test_d0_to_ks_kp_km.py
- tests/channels/test_y_to_d0_d0bar_pi0_pi0.py
- tests/unit/amplitude/test_yaml_canonical.py
- tests/unit/amplitude/test_yaml_helicity.py
Currently the expertsystem and tensorwaves are not compatible, as the highest level `NormalizedIntensity` is missing but is required when performing fits in tensorwaves.
To simplify things I propose the following:
We officially remove this highest level `NormalizedIntensity` as this is only required by fitting using a log likelihood estimator and belong there. This has several advantages:
1. It makes the amplitude model simpler as the normalization is not needed for the intensity definition
2. Data generation is fast as the normalization is skipped
3. The construction of the intensity in tensorwaves becomes more transparent
```python3
builder = IntensityBuilder(part_list, kinematics) # note: the phase space sample here is optional
intensity = builder.create_intensity(model)
data_sample = …
```
> fix: officially remove top NormalizedIntensity

- src/expertsystem/amplitude/helicity_decay.py
- tests/unit/amplitude/test_parity_prefactor.py
Decouple coefficients of amplitudes which are parity violating, by generating the correct coefficient names.
Closes #419
> fix: decouple parity violating amplitudes

- .github/release-drafter.yml
- .github/workflows/requirements-cron.yml
- labels.toml
Issue labels are used not only for the project board, but also used by the Release Drafter. The sections there are currently not clear enough, in particular a distinct section for interface changes was missing.
> ci: add issue label for interface changes

- src/expertsystem/io/_dict/dump.py
- tests/unit/io/test_dict.py
- tests/unit/test_io.py
Tests should make sure that the framework dumps in the correct format. JSON validation is only relevant for input (e.g. a hand-written amplitude model or particle list).
> fix: avoid validating when building dict

- tox.ini
Fixes a bug introduced by #356: the `src` folder does not contain an `__init__.py` file, so `mypy` ignores it if you run `mypy .`.
> ci: run mypy on src folder

- src/expertsystem/amplitude/model.py
- src/expertsystem/io/_dict/build.py
- tests/unit/io/test_dict.py
Allows one to set a custom `Dynamics` class for a particle, as long as it derives from `Dynamics`.
Closes #424
> refactor: make ParticleDynamics mutable

- .github/workflows/ci.yml
Pyright seems to [result in false-positives](https://github.com/ComPWA/expertsystem/runs/1680505840), so we have to temporarily pin `pyright` to 1.1.99. Keep an eye on the Pyright [issues](https://github.com/microsoft/pyright/issues) and [releases](https://github.com/microsoft/pyright/releases).
> ci: pin Pyright to version 1.1.99

- docs/usage/additional_particles.yml
- src/expertsystem/additional_particle_definitions.yml
- src/expertsystem/amplitude/helicity_decay.py
- src/expertsystem/amplitude/model.py
- src/expertsystem/io/__init__.py
- src/expertsystem/io/_dict/build.py
- src/expertsystem/io/_dict/dump.py
- src/expertsystem/io/_dict/validate.py
- src/expertsystem/schemas/amplitude-model.json
- src/expertsystem/schemas/particle-list.json
- tests/unit/amplitude/test_model.py
- tests/unit/io/expected_recipe.yml
- tests/unit/io/test_dict.py
- tests/unit/test_io.py
The `io` module now uses `attr.asdict` where possible. This has a few consequences:
1. classes that are constructed with `attr.s` can be refactored without having to worry about the `io` module.
2. the amplitude model file changes along with the structure of the data classes
3. the code of the `io` module becomes simpler. This is a step towards removing this module (see e.g. #400)
> refactor!: use attr.asdict in io module

- src/expertsystem/amplitude/model.py
- src/expertsystem/io/_dict/build.py
- tests/unit/io/expected_recipe.yml
Addresses https://github.com/ComPWA/expertsystem/pull/436#discussion_r555325425
Alternative would be to rethink the concept of a `FitParameter`: that the value can be `float` or `complex`, or that you can have different types of `FitParameter`. See also https://github.com/ComPWA/expertsystem/issues/397#issuecomment-757542544.
> refactor: rename pole to real and imag

- cspell.json
- docs/conf.py
- reqs/3.6/requirements-doc.txt
- reqs/3.7/requirements-doc.txt
- reqs/3.8/requirements-doc.txt
- reqs/3.9/requirements-doc.txt
- reqs/requirements-dev.in
- reqs/requirements-doc.in
- tox.ini
`pydeps` slows down RTD and the CI, especially when more dependencies are added. Compare:
- 1:43 min https://github.com/ComPWA/expertsystem/runs/1722740664 (58700db on master)
- 1:15 min https://github.com/ComPWA/expertsystem/runs/1722788674 (7e99d87 on this branch)
> docs: remove module visualization

- .github/workflows/linkcheck.yml
- .github/workflows/release-drafter.yml
- .github/workflows/requirements-cron.yml
Allows to run linkcheck, the release drafter and the requirements updater manually, see [here](https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow).
> ci: add GitHub Actions workflow dispatch

- docs/conf.py
Fixes a problem that was introduced by #463:
[`sphinx-math-dollar`](https://www.sympy.org/sphinx-math-dollar) has now been added as a MyST extension, as well as some others.
> fix: add math-dollar and other myst extensions

- docs/adr.md
- docs/adr/001.md
- docs/adr/template.md
The sections of the ADR template has been reorganized as to agree more with upcoming ADRs #458 #461 #467. The idea is that an ADR becomes a bit more like an analysis: state the problem, list requirements of a possible solution, propose some solution, evaluate, and decide which solution to follow.
> adr: reorganize ADR template

- src/expertsystem/reaction/topology.py
- tests/unit/reaction/test_combinatorics.py
- tests/unit/reaction/test_system_control.py
- tests/unit/reaction/test_topology.py
- tox.ini
_Spin-off from #470_
Sometimes test fails for reasons that could have been pointed out with static typing. This PR fixes some of those problems by narrowing down the type hints.
> fix: narrow down type hints

- src/expertsystem/amplitude/canonical_decay.py
- src/expertsystem/amplitude/helicity_decay.py
- src/expertsystem/io/_dot.py
- src/expertsystem/reaction/__init__.py
- src/expertsystem/reaction/combinatorics.py
- src/expertsystem/reaction/solving.py
- src/expertsystem/reaction/topology.py
- tests/unit/reaction/test_solving.py
Many existing interfaces use `Sequence` where the implementation only iterates over the sequence. So `Iterable` (and in one case `Sized`) is more appropriate.
Note: this allows switching from `list` to `set`, see #470.
> fix: use Iterable or Sized where possible

- src/expertsystem/reaction/__init__.py
- src/expertsystem/reaction/_system_control.py
- src/expertsystem/reaction/topology.py
- tests/unit/reaction/test_system_control.py
The `StateTransitionGraph.compare` method provides a sufficient handle to compare graphs. So better not to have an STG carry around its own comparator (the `STG` is in first instance just a mapping of edge and node properties for some underlying topology).
> refactor: remove graph_node_comparator from STG

- src/expertsystem/reaction/topology.py
#460 decorated the `StateTransitionGraph` with `attr.s` and set its members to `frozen`. However, `edge_props` and `node_props` are `dict`s, meaning that you can still modify their values (and even their keys by using `pop` etc.). So, if we want the `StateTransitionGraph` to be truly frozen, their attributes can only be exposed if they are frozen themselves as well. See also #470.
Note: some additional checks have been added on the constructor of the `STG`.
> fix: protect members of StateTransitionGraph

- docs/conf.py
- src/expertsystem/amplitude/canonical_decay.py
- src/expertsystem/amplitude/helicity_decay.py
- src/expertsystem/amplitude/model.py
- src/expertsystem/io/_dot.py
- src/expertsystem/reaction/__init__.py
- src/expertsystem/reaction/_system_control.py
- src/expertsystem/reaction/combinatorics.py
- src/expertsystem/reaction/solving.py
- src/expertsystem/reaction/topology.py
- tests/channels/test_jpsi_to_gamma_pi0_pi0.py
- tests/unit/amplitude/test_parity_prefactor.py
- tests/unit/io/test_dot.py
- tests/unit/reaction/test_solving.py
- tests/unit/reaction/test_system_control.py
- tests/unit/reaction/test_topology.py
The `StateTransitionGraph` is a mapping of properties onto an underlying topology structure. It therefore behaves like a collection of `dict`s, whether the keys are the edge and node IDs of the topology. Currently, the underlying `Topology` is, however, mutable and therefore does not serve well as a collection to map properties onto.
This results in subtle bugs. For instance, the `StateTransitionGraph` falsely protects its underlying `Topology` by dundering it and not exposing it as a `property`. I say falsely, because the `Topology.edges` are still exposed (example from the `stable` branch):
https://github.com/ComPWA/expertsystem/blob/1fb82ffabb1d384454b3790f7689e215ade12f73/src/expertsystem/reaction/topology.py#L369-L371
This allows one to modify the underlying topology as follows: …
> feat: freeze Topology class

- docs/usage/workflow.ipynb
- src/expertsystem/reaction/__init__.py
- src/expertsystem/reaction/solving.py
Violated rules are now raised as an exception. This simplifies the `Result` class: it only contains a formalism type and a list of `StateTransitionGraph`s.
> refactor: raise violated rules as exception

- docs/usage/visualization.ipynb
- docs/usage/workflow.ipynb
- src/expertsystem/amplitude/helicity_decay.py
- src/expertsystem/reaction/__init__.py
- tests/channels/test_d0_to_ks_kp_km.py
- tests/channels/test_jpsi_to_gamma_pi0_pi0.py
- tests/channels/test_y_to_d0_d0bar_pi0_pi0.py
- tests/unit/amplitude/test_model.py
- tests/unit/amplitude/test_parity_prefactor.py
- tests/unit/io/test_dot.py
The `Result` class by now (#459) is just a container with a `solutions` list and a `formalism_type`. In the long term, the idea is that `generate_transitions` only returns `transitions` as a `StateTransitionCollection` object (see #458) and that a `formalism_type` does not have to be carried around within the `reaction` module (#168).
In preparation to this, the variable names are shifting from `graph`/`solution` to `transition`.
> refactor: rename solutions to transitions

- src/expertsystem/reaction/__init__.py
Makes the exception message more readable. Previously, only the entire edge ID to rule mapping `dict` was dumped.
> fix: improve exception message violated rules

- reqs/3.6/requirements-dev.txt
- reqs/3.7/requirements-dev.txt
- reqs/3.8/requirements-dev.txt
- reqs/3.9/requirements-dev.txt
- reqs/requirements-dev.in
- tox.ini
#466 removed `jupyterlab-code-formatter` because `nbqa` formatting and `jupyterlab-code-formatter` slightly differ in style. `jupyterlab-code-formatter` is, however, quite a handy tool while working on notebooks, despite the eventual formatting differences.
> ci: add back jupyterlab-code-formatter

- src/expertsystem/reaction/__init__.py
- src/expertsystem/reaction/topology.py
_Spin-off from #454_
`Topology` classes that are created by the `SimpleStateTransitionTopologyBuilder` are sorted randomly because the hash of `Topology` is not suitable for sorting. Therefore it's better to return a `tuple` of `Topology`'s.
> refactor: let Topology builder return tuple

- docs/_templates/module.rst_t
- docs/_templates/package.rst_t
> docs: render module import line on API pages

- docs/adr/001/operators.ipynb
- docs/adr/002/composition.ipynb
- docs/adr/002/expr.ipynb
- docs/adr/002/function.ipynb
Somehow if a Jupyter notebook contains
```
"nbformat_minor": 5
```
in its [top-level structure](https://ipython.org/ipython-doc/dev/notebook/nbformat.html#top-level-structure), instead of
```
"nbformat_minor": 4
```
both `nbstripout` and Jupyter lab add randomly generated cell IDs to each cell. This is super bothersome for diffs and merge conflicts. Worst part is that the IDs are random which causes a lot of unnecessary file changes.
This PR removes the `"id"` items and lowers the `nbformat_minor`. With the current dev set-up (pinned versions of `jupyterlab` etc) new notebooks will again get `"nbformat_minor": 5`, but I'm not sure how to work around this. Just something to keep an eye on now.
> fix: remove cell ids from notebooks

- src/expertsystem/reaction/topology.py
- tests/unit/io/test_dot.py
- tests/unit/reaction/test_system_control.py
- tests/unit/reaction/test_topology.py
Even though the constructor `Topology` allows one to use `nodes={0, 1}` (the `set` is cast internally to a `frozenset`), `mypy` says this is not allowed. This PR fixes this behaviour.
> fix: allow Iterable in Topology constructor

- src/expertsystem/reaction/__init__.py
- src/expertsystem/reaction/topology.py
- tests/unit/reaction/test_combinatorics.py
- tests/unit/reaction/test_topology.py
`create_isobar_topologies` now only needs a number of final states: it is assumed that the number of initial states is one.
> fix: create_isobar_topologies only requires n_final

- docs/usage/visualization.ipynb
- src/expertsystem/io/__init__.py
- src/expertsystem/io/_dot.py
- tests/unit/io/test_dot.py
- The visualize page now also illustrates how to visualize topologies.
- It's now possible to run `convert_to_dot` on a `tuple` as well. This is required if one wants to do:
```python
from expertsystem.io import convert_to_dot
from expertsystem.reaction.topology import create_isobar_topologies
convert_to_dot(create_isobar_topologies(4))
```
because `create_isobar_topologies` returns a `tuple`.
- Node IDs are also rendered in DOT if there is more than one node
> docs: visualize Topology with node IDs

- reqs/3.6/requirements-dev.txt
- reqs/3.6/requirements-doc.txt
- reqs/3.6/requirements-sty.txt
- reqs/3.6/requirements-test.txt
- reqs/3.6/requirements.txt
- reqs/3.7/requirements-dev.txt
- reqs/3.7/requirements-doc.txt
- reqs/3.7/requirements-sty.txt
- reqs/3.7/requirements-test.txt
- reqs/3.7/requirements.txt
- reqs/3.8/requirements-dev.txt
- reqs/3.8/requirements-doc.txt
- reqs/3.8/requirements-sty.txt
- reqs/3.8/requirements-test.txt
- reqs/3.8/requirements.txt
- reqs/3.9/requirements-dev.txt
- reqs/3.9/requirements-doc.txt
- reqs/3.9/requirements-sty.txt
- reqs/3.9/requirements-test.txt
- reqs/3.9/requirements.txt
- reqs/requirements-dev.in
Adds [`aquirdturtle-collapsible-headings`](https://pypi.org/project/aquirdturtle-collapsible-headings) to the dev requirements. Activates directly through `pip` install since Jupyter Lab v3, so no need to call `jupyter labextension install`. Helps to keep notebooks organised while working on them:
> ci: add collapsible_headings labextension

- src/expertsystem/reaction/topology.py
- src/expertsystem/schemas/amplitude-model.json
- tests/unit/amplitude/test_model.py
- tests/unit/io/expected_recipe.yml
- tests/unit/io/test_dict.py
- tests/unit/reaction/test_combinatorics.py
- tests/unit/reaction/test_solving.py
- tests/unit/reaction/test_topology.py
The `SimpleStateTransitionTopologyBuilder` now creates topologies that are labeled in such a way that:
- initial edges are labeled `[-1, -2, ...]`
- final edges are labeled `[0, 1, 2, ..., n]`
- intermediate edges are labeled `[n+1, n+2, ...]`
This way, final state and intermediate state edge IDs are always within the same domain, no matter the underlying topology.
**Old (9ea200a9)**
|  |  |  |
| --- | --- | --- |
| ![image](https://user-images.githubusercontent.com/29308176/109818216-0987c080-7c33-11eb-9a7b-9221570ecb02.png) | ![image](https://user-images.githubusercontent.com/29308176/109818239-0f7da180-7c33-11eb-8402-f7987058c614.png) | ![image](https://user-images.githubusercontent.com/29308176/109818392-39cf5f00-7c33-11eb-8dc0-5f280303b0bd.png) |
**New (2579a837)**
|  |  |  |
| --- | …
> refactor: relabel edge IDs to range [-m, n+i]

- reqs/3.6/requirements-dev.txt
- reqs/3.6/requirements-doc.txt
- reqs/3.6/requirements-sty.txt
- reqs/3.7/requirements-dev.txt
- reqs/3.7/requirements-doc.txt
- reqs/3.7/requirements-sty.txt
- reqs/3.8/requirements-dev.txt
- reqs/3.8/requirements-doc.txt
- reqs/3.8/requirements-sty.txt
- reqs/3.9/requirements-dev.txt
- reqs/3.9/requirements-doc.txt
- reqs/3.9/requirements-sty.txt
- setup.cfg
- src/expertsystem/reaction/__init__.py
Previously, the progress bar was using a `tqdm` instance for console, which results in rendering errors in notebooks. This PR uses `from tqdm.auto import tqdm`. See https://github.com/tqdm/tqdm#ipythonjupyter-integration
Unfortunately, the bar is now also rendered in the docs
This is because `autonotebook` is unaffected by
https://github.com/ComPWA/expertsystem/blob/22d6f67dec4716d9d0bddc197c230efb46313e1e/docs/conf.py#L208
(see https://myst-nb.readthedocs.io/en/latest/use/formatting_outputs.html#removing-stdout-and-stderr)
> fix: use tqdm.autonotebook

- docs/usage.ipynb
- docs/usage/visualization.ipynb
- src/expertsystem/io/__init__.py
- src/expertsystem/io/_dot.py
_Extracted from #454 and extended with options to configure_
Result:
Since #504, edge IDs have become more important because they are the same as the final state IDs (at least when considering output that comes from the `reaction` module).
In addition, it's possible to switch off node edge ID rendering.
> feat: render edge IDs in graph visualization

- src/expertsystem/reaction/__init__.py
- src/expertsystem/reaction/default_settings.py
Allows to set the mass conservation factor that was introduced by #484 to the STM through the `generate_transitions` facade as well.
> feat: add mass conservation factor to generate_transitions

- cspell.json
- docs/usage/reaction.ipynb
- docs/usage/visualize.ipynb
- src/expertsystem/__init__.py
- src/expertsystem/io/__init__.py
- src/expertsystem/io/_dict.py
- src/expertsystem/io/_dot.py
- src/expertsystem/reaction/__init__.py
- src/expertsystem/reaction/default_settings.py
- src/expertsystem/reaction/quantum_numbers.py
- src/expertsystem/reaction/topology.py
- tests/conftest.py
- tests/unit/io/test_io.py
Allow to serialize `Result`, `StateTransitionGraph[ParticleWithSpin]`, and `Topology` to and from `dict` with `io.asdict`/`io.fromdict` so that they can be written to disk with `io.write`. This is useful if it takes a long time to generate transitions.
Some changes were required:
- `load_default_particles` had to be moved to the top import, so that the `reaction` module is not dependent on the `io` module (the type hint for `Result` in the `io` introduces a circular dependency).
- Some converters were added to the `attr`-decorated classes that are being serialized, so that they still work after serializing to and from JSON (which has `str` keys only).
- Added a 'strict' `__eq__` method for `StateTransitionGraph` for testing.
> feat: export and import transitions to JSON/YAML

- src/expertsystem/io/_dot.py
Previously, what's shown below would have `1.0` and `0.0` spin projections due to a bug in `io._dot`
> fix: show spin projections as int

- docs/usage/amplitude.ipynb
- docs/usage/dynamics/custom.ipynb
- src/expertsystem/amplitude/helicity.py
- tests/channels/test_d0_to_ks_kp_km.py
- tests/channels/test_y_to_d0_d0bar_pi0_pi0.py
- tests/unit/amplitude/test_angular_distributions.py
- tests/unit/amplitude/test_helicity.py
- tests/unit/amplitude/test_parity_prefactor.py
This naming makes more sense, as `HelicityModel.parameters` sounds like some sequence that lists the parameters in the model, while it's actually a mapping of those parameters to default ('suggested') values.
> refactor: rename parameters to parameter_defaults

- .pre-commit-config.yaml
- .pre-commit-hooks/fix_first_nbcell.py
- .pre-commit-hooks/fix_nbformat_version.py
- .pre-commit-hooks/set_first_cell.py
- docs/usage.ipynb
- docs/usage/amplitude.ipynb
- docs/usage/dynamics/custom.ipynb
- docs/usage/dynamics/lineshapes.ipynb
- docs/usage/particle.ipynb
- docs/usage/reaction.ipynb
- docs/usage/visualize.ipynb
_Follow-up to https://github.com/ComPWA/expertsystem/pull/497_
Added some example scripts that automatically apply some more formatting to the jupyter notebooks as pre-commit hooks.
Note that it's better to host such scripts under a separate 'hook' repository, like [this one](https://github.com/pre-commit/pre-commit-hooks). But this would move in the direction of standardizing the dev environment through a third repository (like that PWA packes, if that were to have versioning).
> ci: add custom pre-commit hooks for notebooks

- .github/release-drafter.yml
The release drafter previously only added PR titles to the release notes. Now the body is also included.
> ci: add PR message to release notes

- src/expertsystem/particle/__init__.py
- src/expertsystem/reaction/_system_control.py
- tests/unit/particle/test_particle.py
Makes the two classes easier to read and maintain. Also offers the possibility to add [converters](https://www.attrs.org/en/20.3.0/examples.html#conversion) and [validators](https://www.attrs.org/en/20.3.0/examples.html#validators).
> refactor: decorate Parity and Spin with attrs

- docs/usage/particle.ipynb
- src/expertsystem/particle/__init__.py
- tests/unit/particle/test_particle.py
This makes it easier to define a custom `Particle`, because it's not necessary to import and declare `Parity` and `Spin` instances first. For instance:
```python
Particle(
name="custom",
pid=99999,
latex=R"p_\mathrm{custom}",
spin=1.0,
mass=1,
charge=1,
isospin=(1.5, 0.5),  # no need to use Spin
charmness=1,
parity=+1,  # no need to use Parity
)
```
> feat: add Particle argument converters

- docs/usage.ipynb
- docs/usage/visualize.ipynb
- src/expertsystem/io/__init__.py
- src/expertsystem/io/_dot.py
Argument `render_edge_id` in `asdot` has been split into `render_final_state_id`, `render_resonance_id`, and `render_initial_state_id`.
Edges IDs of initial states and resonances are now hidden by default. They can be shown with the arguments of `asdot`:
```python
import expertsystem as es
es.io.asdot(
graphs,
render_node=True,
render_final_state_id=True,
render_resonance_id=True,
render_initial_state_id=True,
collapse_graphs=True,
)
```
Default view of a `StateTransitionGraph`:
> feat: allow hiding initial state and resonance ids

- src/expertsystem/particle/__init__.py
- tests/unit/particle/test_particle.py
Use [`diflib`](https://docs.python.org/3/library/difflib.html) to find more particle candidates in case [`startswith`](https://docs.python.org/3/library/stdtypes.html#str.startswith) fails to find any. For instance:
```python
>>> from expertsystem.particle import load_pdg
>>> pdg = load_pdg()
>>> pdg["lambda"]
Traceback (most recent call last):
...
KeyError: "No particle with name 'lambda' in the database. Did you mean one of these? ['Lambda', 'Lambda~', 'Lambda(c)+', 'Lambda(b)0']"
>>> pdg["gamm"]
Traceback (most recent call last):
...
KeyError: "No particle with name 'gamm' in the database. Did you mean 'gamma'?"
```
> fix: improve ParticleCollection.find exception

- .github/workflows/ci.yml
- .pre-commit-config.yaml
- tox.ini
[cSpell](https://github.com/streetsidesoftware/cspell) is now enforced through [`pre-commit`](https://github.com/ComPWA/mirrors-cspell). This means that there is no need anymore to install cSpell through `npm` and that spelling is checked upon committing :tada: 
For more info, see [github.com/ComPWA/mirrors-cspell](https://github.com/ComPWA/mirrors-cspell).
> ci!: run cspell as pre-commit hook
